version: '3.8'

services:

  nginx:
    build: ./nginx
    container_name: ${PROJECT_SLUG}_nginx
    volumes:
      - static_dir:/opt/src/static/
      - media_dir:/opt/src/media/
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - nginx_network

  web:
    build:
      context: ./src
      dockerfile: backend.dockerfile
    container_name: ${PROJECT_SLUG}_app
    working_dir: /opt/src
    volumes:
      - static_dir:/opt/src/static/
      - media_dir:/opt/src/media/
      - ./src:/opt/src:rw
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - nginx_network


  db:
    image: postgres:latest
    container_name: ${PROJECT_SLUG}_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - nginx_network


volumes:
  static_dir:
  media_dir:
  pgdata:

networks:
  nginx_network: